<?php

namespace Tests\Unit;

use App\Exports\MemberTemplateExport;
use Tests\TestCase;

class MemberTemplateExportTest extends TestCase
{
    /**
     * Test: Member template does NOT have nik column.
     * Member number is generated by system, not from Excel.
     */
    public function test_template_has_no_nik_column(): void
    {
        $export = new MemberTemplateExport();
        $headings = $export->headings();

        // nik should NOT be in headings
        $this->assertNotContains('nik', $headings);
        $this->assertNotContains('NIK', $headings);
        $this->assertNotContains('nomor_anggota', $headings);
    }

    /**
     * Test: Member template has correct columns for data input.
     */
    public function test_template_has_required_columns(): void
    {
        $export = new MemberTemplateExport();
        $headings = $export->headings();

        // Required data columns
        $requiredColumns = [
            'nama',
            'tempat_lahir',
            'tanggal_lahir',
            'alamat',
            'jenis_kelamin',
            'agama',
            'berlaku_hingga',
            'tanggal_pembuatan',
            'foto',
        ];

        foreach ($requiredColumns as $column) {
            $this->assertContains($column, $headings, "Missing required column: {$column}");
        }
    }

    /**
     * Test: Member template has company columns.
     */
    public function test_template_has_company_columns(): void
    {
        $export = new MemberTemplateExport();
        $headings = $export->headings();

        $this->assertContains('kode_perusahaan', $headings);
        $this->assertContains('nama_perusahaan', $headings);
    }

    /**
     * Test: Member template example uses correct photo filename format.
     * Photo should use company code + sequence, not nik.
     */
    public function test_template_uses_correct_photo_format(): void
    {
        $export = new MemberTemplateExport();
        $collection = $export->collection();
        $firstRow = $collection->first();

        // Example should NOT use old NIK format for photo
        $this->assertNotEquals('3275010101900001.jpg', $firstRow['foto']);

        // Should use company-based format
        $this->assertStringContainsString('ABC', $firstRow['foto']);
        $this->assertStringContainsString('.jpg', $firstRow['foto']);
    }
}
